kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mlplatform-backend-role-{{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - pods/log
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - patch

- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete

- apiGroups:
  - serving.kubeflow.org
  resources:
  - inferenceservices
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
