apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlplatform-backend-pvc-{{ .Release.Name }}
spec:
  storageClassName: {{ .Values.backend.volume.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backend.volume.size }}