kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mlplatform-backend-rolebinding-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: mlplatform-backend-sa-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: mlplatform-backend-role-{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
