apiVersion: v1
kind: Service
metadata:
  name: mlplatform-frontend-svc-{{ .Release.Name }}
  labels:
    app: mlplatform-frontend-svc-{{ .Release.Name }}
spec:
  ports:
  - name: server-port
    port: 80
    {{ if eq .Values.frontend.service.type "NodePort" }}
    nodePort: {{ required "frontend nodePort must be set if service type is 'NodePort'" .Values.frontend.service.nodePort }}
    {{ end }}
    targetPort: 80
    protocol: TCP
  selector:
    app: mlplatform-frontend-deploy-{{ .Release.Name }}
  type: {{ .Values.frontend.service.type }}