global:
  registry:
    address:
    imagePullSecret: 

  loadbalancer:
    enabled: true
    ip: 192.168.179.39
    port: 8080
    isHttps: true

  db:
    address: tiberolocaldns
    port: 8629
    persistentVolumeClaimName: tibero-pvc-db
    mountPath: /db

image:
  name: hyperdata20_hd
  tag: 20210820182035

version:
  major: 20

proxy:
  bodysize: 1024m
  # minutes
  timeout: 1800

kca:
  address: svc-kca
  port: 5000

resources:
  cpu: 2
  memory: 4Gi
