apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlplatform-backend-sa
secrets:
  - name: mlplatform-backend-secret
{{ if .Values.global.registry.imagePullSecret }}
  - name: {{ .Values.global.registry.imagePullSecret }}
{{ end }}