registry:
  address: 192.168.179.44:5000
  secret: mlplatform-harbor-regcred


hyperdata:
  address: http://hyperdata-svc-hd:8000


proauth:
  address: http://hyperdata-lb-hd:28080

kubernetes:
  istio:
    ingressgateway:
      ip: 192.168.179.31
      port: 31380


backend:
  image:
    name: hyperdata20.4_mlplatform_backend
    tag: 20210820_v1
    imagePullPolicy: Always
  resources:
    requests:
      cpu: 1
      memory: 1G
    limits:
      cpu: 1
      memory: 1G
  volume:
    storageClass:
    size: 10Gi
    mountPath: /mlplatform

frontend:
  image:
    name: hyperdata20.4_mlplatform_frontend
    tag: 20210820_v1
    imagePullPolicy: Always
  service:
    type: ClusterIP
    nodePort: ""
  resources:
    requests:
      cpu: 1
      memory: 1G
    limits:
      cpu: 1
      memory: 1G

models:
  recommendation:
    image:
      name: hyperdata20.4_mlplatform_recommendation
      tag: 20210827_v1
      imagePullPolicy: Always
