registry:
  address: 192.168.179.44:5000
  # imagePullSecret이 존재하지 않을 경우, knaive-serving은 동작하지 않는다.
  secret: mlplatform-backend-secret


hyperdata:
  address: http://hyperdata-svc-hd:8080


proauth:
  address: http://hyperdata-lb-hd:28080

kubernetes:
  istio:
    ingressgateway:
      ip: 192.168.179.31
      port: 31380
      namespace: istio-system
      service:
        name: istio-ingressgateway


backend:
  image:
    name: hyperdata20.4_mlplatform_backend
    tag: 20210820_v1
    imagePullPolicy: Always
  resources:
    requests:
      cpu: 1
      memory: 1G
    limits:
      cpu: 1
      memory: 1G
  volume:
    storageClass: ceph-filesystem
    size: 10Gi
    mountPath: /mlplatform

frontend:
  image:
    name: hyperdata20.4_mlplatform_frontend
    tag: 20210820_v1
    imagePullPolicy: Always
  service:
    type: ClusterIP
    nodePort: ""
  resources:
    requests:
      cpu: 1
      memory: 1G
    limits:
      cpu: 1
      memory: 1G

models:
  recommendation:
    image:
      name: hyperdata20.4_mlplatform_recommendation
      tag: 20210827_v1
      imagePullPolicy: Always

automl:
  image:
    name: hyperdata20.4_automl
    tag: 20210827_v1