image: apache/ozone:1.0.0

#csi:
#  registrar:
#    image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.2
#  provisioner:
#    image: quay.io/k8scsi/csi-provisioner:v1.0.1

om:
  replicas: 1
  resources:
    limits:
      cpu: "4000m"
      memory: "4000Mi"
    requests:
      cpu: "1000m"
      memory: "500Mi"
  storage:
    size: 2Gi
  service:
    type: NodePort

scm:
  replicas: 1
  resources:
    limits:
      cpu: "4000m"
      memory: "4000Mi"
    requests:
      cpu: "1000m"
      memory: "500Mi"
  storage:
    size: 2Gi
  service:
    type: NodePort

datanode:
  replicas: 3
  resources:
    limits:
      cpu: "4000m"
      memory: "4000Mi"
    requests:
      cpu: "1000m"
      memory: "500Mi"
  storage:
    size: 2Gi

s3g:
  replicas: 1
  resources:
    limits:
      cpu: "4000m"
      memory: "4000Mi"
    requests:
      cpu: "1000m"
      memory: "500Mi"
  storage:
    size: 2Gi
  service:
    type: NodePort

