image: 192.168.179.44:5000/hyperdata20.4_virtualization:20220415_v1

proxy:
  bodysize: 1024m
  # minutes
  timeout: 1800

proxy:
  bodysize: 1024m
  # minutes
  timeout: 1800

server:
  port: 8100
  servlet:
    contextPath: /hyperdata8

db:
  address: tiberolocaldns
  port: 8629
  sid: tibero

pvc:
  name: tibero-pvc-db
  mountPath: /db

resources:
  cpu: 2
  memory: 4Gi

proauth:
  address: lb-hd-dev40:28080

hyperdata:
  address: svc-hd-dev40
  port: 8080

loadBalancer:
  enabled: true
  ip: 192.168.179.42 #하이퍼데이터 로드밸런서 ip랑 같아야 함
  extport: 8500

logging:
  path: virtualization/logs