# permissions for end users to edit hyperdata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hyperdata-editor-role
rules:
- apiGroups:
  - hyperdata.tmax.io
  resources:
  - hyperdata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hyperdata.tmax.io
  resources:
  - hyperdata/status
  verbs:
  - get
