image: 192.168.179.44:5000/hyperdata8.3_tb:20210811_v1

loadbalancer:
  enabled: true
  ip: <YOUR EXTERNAL_IP or MASTER NODE's IP>

db:
  persistentVolumeClaimName: tibero-pvc-db
  mountPath: /db

shmSize: 2Gi

resources:
  cpu: 2
  memory: 4Gi
  storage: 40Gi