apiVersion: v1
kind: Pod
metadata:
  labels:
    lb: {{ .Release.Namespace }}-hd
  name: {{ .Release.Namespace }}-pod-hd-hd
spec:
  containers:
  - env:
    - name: WEBSERVER_IP
      value: {{ .Values.webserver.ip }}
    - name: WEBSERVER_PORT
      value: "{{ .Values.webserver.port }}"
    - name: TB_PORT
      value: "8629"
    - name: TB_SID
      value: "tibero"
    - name: HLADMIN_PORT
      value: "23000"
    - name: KUBEFLOW_PORT
      value: "{{ .Values.kubeflow.ports.notebook }}"
    - name: RECOMMEND_SERVER_PORT
      value: "5000"
    - name: KUBEFLOW_IP
      value: {{ .Values.kubeflow.ip }}
    - name: KUBEFLOW_USER
      value: root
    - name: KUBEFLOW_PW
      value: tibero
    - name: TB_IP
      value: 10.244.48.110
    - name: HLADMIN_IP
      value: 10.244.184.122
    - name: RECOMMEND_SERVER_IP
      value: 10.244.170.209
#    - name: SKIP_RECREATE_SCHEMA
#      value: "Y"
#    - name: SKIP_RECREATE_ROLE_AND_PERMISSION
#      value: "Y"
#    - name: SKIP_RECREATE_ADMIN
#      value: "Y"
#    - name: USE_REALTIME
#      value: "Y"
    - name: SSH_PORT
      value: "22"
    - name: IS_PRIVATE_DOCKER
      value: "true"
    - name: IS_HYPER_CLOUD
      value: "false"
    - name: PRIVATE_DOCKER_IP
      value: {{ .Values.registry.ip }}
    - name: PRIVATE_DOCKER_PORT
      value: "{{ .Values.registry.port }}"
    - name: SECRET_NAME
      value: {{ .Values.registry.secret }}
    - name: AUTOML_FRONTEND
      value: {{ .Values.automl.frontend }}
    - name: AUTOML_BACKEND
      value: {{ .Values.automl.backend }}
    - name: AUTOML_NAMESPACE
      value: {{ .Release.Namespace }}
    - name: HADOOP_ALIAS
      value: "127.0.0.1 alias1 alias2"
    - name: IS_HTTPS
      value: "{{ .Values.https.enabled }}"
    - name: USE_MQTT_LB
      value: "Y"
    - name: MQTT_BROKER_IP
      value: {{ .Values.webserver.ip }}
    - name: MQTT_BROKER_PORT
      value: "{{ .Values.webserver.port }}"
    - name: MQTT_BROKER_WS_PORT
      value: ""
    - name: SSL_CERT_IP_ADDRESS
      value: ""
    image: {{ .Values.image }}
    imagePullPolicy: IfNotPresent
    name: {{ .Release.Namespace }}-con-hd-hd
    ports:
    - containerPort: 20
      name: hd-ftp1
      protocol: TCP
    - containerPort: 21
      name: hd-ftp2
      protocol: TCP
    - containerPort: 22
      name: hd-ssh
      protocol: TCP
    - containerPort: 9736
      name: jeus-http
      protocol: TCP
    - containerPort: 8080
      name: hd-http
      protocol: TCP
    - containerPort: 1883
      name: msqt-lsnr1
      protocol: TCP
    - containerPort: 2883
      name: msqt-lsnr2
      protocol: TCP
    - containerPort: 1408
      name: hd-web
      protocol: TCP
    resources:
      limits:
        cpu: "4"
        memory: "8Gi"
      requests:
        cpu: "4"
        memory: "8Gi"
    volumeMounts:
    - name: tz-seoul
      mountPath: /etc/localtime
    - mountPath: /db
      name: pv-storage
  volumes:
  - name: tz-seoul
    hostPath:
      path: /usr/share/zoneinfo/Asia/Seoul
  - name: pv-storage
    persistentVolumeClaim:
      claimName: {{ .Release.Namespace }}-pvc-db
