apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hyperdata
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]