apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hyperdata
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hyperdata
subjects:
- kind: ServiceAccount
  name: hyperdata
  namespace: {{ .Release.Namespace }}
