apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Namespace }}-hd-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - secretName: istio.{{ .Release.Namespace }}-nginx-ingress-nginx
  rules:
   -  http:
       paths:
       - path: /hyperdata8/(.*)
         backend:
           serviceName: {{ .Release.Namespace }}-svc-hd
           servicePort: 8080
   -  http:
        paths:
        - path: /hyperdata(/|$)(.*)
          backend:
            serviceName: {{ .Release.Namespace }}-svc-hd
            servicePort: 8080
