apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Release.Namespace }}-hd
  name: {{ .Release.Namespace }}-pvc-hd
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10000Mi
  storageClassName: csi-cephfs
  volumeMode: Filesystem
