image: <YOUR REGISTRY IP>:<YOUR PORT>/hyperdata8.3_hd:20210310_v4h

registry:
  ip: <YOUR REGISTRY IP>
  port: <YOUR PORT>
  secret: "no-secret"

https:
  enabled: true

proxy:
  bodysize: 1024m
  # minutes
  timeout: 1800

webserver:
  ip: <YOUR EXTERNAL_IP or MASTER NODE's IP>
  port: 8080

automl:
  frontend: <YOUR EXTERNAL_IP or MASTER NODE's IP>:8080/automl/frontend
  backend: <YOUR EXTERNAL_IP or MASTER NODE's IP>:8080/automl/backend

kubeflow:
  ip: <YOUR ISTIO_Ingress gateway IP or master node's IP>
  ports:
    notebook: 31380

loadbalancer:
  enabled: true

tbMountVolume: /db

resources:
  cpu: 2
  memory: 4Gi