global:
  registry:
    address: 192.168.179.44:5000
    imagePullSecret: 

  loadbalancer:
    enabled: true
    ip: 192.168.179.39
    port: 8080
    isHttps: true

  db:
    address: tiberolocaldns
    port: 8629
    persistentVolumeClaimName: tibero-pvc-db
    mountPath: /db

image:
  name: hyperdata8.3_tb
  tag: 20210811_v1

shmSize: 2Gi

resources:
  cpu: 2
  memory: 4Gi
  storage: 40Gi