apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: {{ .Release.Name }}-hd
  name: {{ .Release.Name }}-pvc-db
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
  storageClassName: csi-cephfs
  volumeMode: Filesystem